### ISSUE TITLE
GTA 5 can not run 

### ISSUE THREAD

**Issue by woodycc** [alienwaresoftware/Kodi#10]
With error 9 social club not completely installed

**Comment by indidevelopers** [comment]
Thank you for Reporting. We have fixed this issue. Soon we will release beta version so please test it and let us know your feedback.

**Comment by indidevelopers** [comment]
Thank you for your feedback! This issue with GTA 5  has been resolved. Please try out our beta version at this link:  https://www.reddit.com/r/AlienwareAlpha/comments/3u940g/hivemind_ui_beta_program/

**Comment by woodycc** [comment]
Fixed, I can play this game now.Thanks
