### ISSUE TITLE
Power

### ISSUE THREAD

**Issue by FregrinZ** [alienwaresoftware/Kodi#12]
I click on power, but non of the available options do anything. I have to shutdown via ctrl alt delete or in steam.

**Comment by indidevelopers** [comment]
Thanks for your feedback! Please let us know are you using beta version as detailed below?

https://www.reddit.com/r/AlienwareAlpha/comments/3u940g/hivemind_ui_beta_program/

**Comment by indidevelopers** [comment]
Also, if you could follow below steps and let us know if HiveMindService and HiveMindMonitor are present and running or not?

Steps:

• If you are presently in Alpha Console Account (HiveMind) then Click on Power Menu -> Go To Desktop.
• If Go to Desktop doesn’t respond then via Keyboard press CTRL+ALT+DELETE, look for the Sign Out Option and Click on it.
• This should take you to the initial Windows logon screen where it shows the option for Desktop Mode (Admin User Account) and Alpha Console Account.  Select and Log-In into your Desktop Mode (Admin User Account)
• Open Task Manager by right-click on the Taskbar, and then click on Task Manager. Or you can open Task Manager by pressing CTRL+SHIFT+ESC.
• Click on the Services tab to see the services that are currently running under your user account.
• Check to see, if HiveMindService is present under Services Tab.
• If HiveMindService is present then check if it is Running or Stopped under Status column.
• If HiveMindService is Running, click on the Detail Tab.
• Under Detail Tab, check if the HiveMindMonitor is running.

**Comment by FregrinZ** [comment]
I believe am using correct beta,I will check your steps above when am home from work..thanks for the replies.

**Comment by FregrinZ** [comment]
Far I can see services are running...and am using beta you linked,if i run the exe file asks do I want to disable the beta.

I also downloaded kodi master zip and copy/paste over some the folders that looked like could be right ones but didnt fix the issue, i tap on power and menu comes up but non of my selections do anything,be it shutdown,sleep or reboot etc. Also doesnt find any of my games only the ones i added manually :(

**Comment by indidevelopers** [comment]
Thanks for the update. Could you please follow below steps and provide screenshot of the screen. 

Use Desktop Mode (Admin User Account)
1.  In Windows 10 or Windows 8.1, right-click on the Start button and then choose Run. 
2.  In the search box, or Run window, type the following: regedit, and then press OK.
3.  You may see a User Account Control dialog box where you'll need to confirm (Press Yes) that you want to open Registry Editor.
4.  Registry Editor Window should open.
5.  Navigate to HEKY_LOCAL_MACHINE > SOFTWARE > HIVEMIND 
6.  On Right-Hand Side of the screen you should see UpdateGameData Key Entry
7.  Please take Screenshot of the screen and post here.

**Comment by FregrinZ** [comment]
Ah sorry I done system restore before seeing your reply,problem now is hivemind won't get press circle when you install and pick console mode..
