### ISSUE TITLE
Beta .63 build - Hotkeys still don't work for Steam and XB1 Controllers

### ISSUE THREAD

**Issue by slyfuldragon** [alienwaresoftware/Kodi#13]
As title above states, the Hotkeys still do not work for the Steam Controller and and XB1 Controller (connected via the XB1 Wireless Receiver). I have been running HiveMind since it was known as AlphaUI at launch, but to get into the beta I uninstalled it then reinstalled it and was able to get into the beta. I have a 1TB SSD with Windows 10 running on the Alpha.

I should also mention that the XB360 hotkeys still work (and have always worked for me), however the XB1 and Steam Controller hotkeys seemed to have not work for me to begin with.

**Comment by indidevelopers** [comment]
Thank you for your feedback! We are aware of the steam issue and are working to fix it!  Xbox One wireless is currently not supported  (xbox One  wired is supported).

**Comment by slyfuldragon** [comment]
Thank you very much for the reply and for the update.
Do you guys have any plans on supporting the XB1 wireless controller (via the Wireless Receiver) in the future? If so, wonderful -- I can patiently wait at that point.
