### ISSUE TITLE
Nvidia Shadow Play

### ISSUE THREAD

**Issue by Salja** [alienwaresoftware/Kodi#4]
You cant start shadow play on the Hivemind ui i think the service for NvidiaStream (Shadow Play) is not startet ?

**Comment by Salja** [comment]
btw on desktop works fine

**Comment by indidevelopers** [comment]
if you know, Can you please let us know which service is required for NvidiaStream (Shadow Play)?

**Comment by Salja** [comment]
![screenshot_1](https://cloud.githubusercontent.com/assets/100154/10712119/b8230082-7a90-11e5-86ed-073e7513ccdb.png)
The Both Streamer Services (Screenshot from Desktop Mode)

**Comment by indidevelopers** [comment]
This Issue is fixed in internal build. We are going release to all very shortly. After fix If still dose not work. Uninstall GFE and reinstall from Desktop (admin account)

**Comment by indidevelopers** [comment]
Today We have push updated . Let us know if this issue is fixed for you

**Comment by indidevelopers** [comment]
Thanks for your feedback! Please try out the beta version at this link to see if the problem you had is resolved: 
https://www.reddit.com/r/AlienwareAlpha/comments/3u940g/hivemind_ui_beta_program/
