### ISSUE TITLE
Controller Issues after launch Webbrowser

### ISSUE THREAD

**Issue by Salja** [alienwaresoftware/Kodi#5]
if you open the Webbrowser (on some other programms same issues) and close him you cant controll the ui with the controller (the stick only shaow mouse icon) , this is not all time but 50% than you must restart the alpha what you can use the controller again

**Comment by indidevelopers** [comment]
Once Webbrowser is open mouse mode enabled. When mouse mode is enabled you can use controller as mouse only can not control UI. You have to disable mouse mode using mouse enable/disable hotkey see help for how to use hotkey

**Comment by Salja** [comment]
i will try thanks some other what about wehn you a programm "Minimize" some trick to relaunch without to restart the programm ? example webbrwoeser i Minimize him and how i can relaunch  ?

**Comment by indidevelopers** [comment]
See hotkey for app switch (task switch same as alt+tab).

**Comment by Salja** [comment]
yeah thanks found =)

**Comment by indidevelopers** [comment]
both issues resolved ?

**Comment by Salja** [comment]
hmm the first issues is a bit strange its hard to wirte with my bad english =) i add as example fraps to my programms, i start frabs and make my settings and close "i use mouse for it" now the programm is closed and the controller not switch back to the ui still have the mouse on controller. im disabled mouse on settings but same result i must logoff and login to the user what i can use the conttroller again

**Comment by Salja** [comment]
"When mouse mode is enabled you can use controller as mouse only can not control UI." yes thats right but when im closing the programm the mouse mode still enabled on controller controll

**Comment by indidevelopers** [comment]
This is working as design you have to manually turn off mouse mode using hotkey. We do not turn off automatically once you close application.

**Comment by Salja** [comment]
ahhhh ok now i understand than i think you can close the issues and thanks for the support =) i hope you can take a look on the other issues by time =)
