### ISSUE TITLE
Netflix issues

### ISSUE THREAD

**Issue by SoundWave6666** [alienwaresoftware/Kodi#6]
Not sure if its a hivemind issue or not, but when I use the quick launch for netflix it opens but tells me I need to be in something called app mode? Cant figure out how to switch it to work.

**Comment by indidevelopers** [comment]
Can you please provide screenshots ?

**Comment by indidevelopers** [comment]
Thanks for your feedback! Please try out the beta version at this link to see if the problem you had is resolved: 
https://www.reddit.com/r/AlienwareAlpha/comments/3u940g/hivemind_ui_beta_program/
