### ISSUE TITLE
Hotkeys have stopped functioning

### ISSUE THREAD

**Issue by dmillerzx** [alienwaresoftware/Kodi#7]
Hotkeys for controllers have stopped working for me.  It seems the hivemindservice or hivemindmonitor might be having some sort of issue at boot.

Initially I never had a problem with hotkeys, it might only be present only in the latest version of hivemind.  I've reinstalled the hivemind software using my service tag on Dell's site to ensure everything was back to the defaults per the latest version of hivemind.  

Initially hot keys were working after booting back into hivemind and I was able to toggle cursor mode.  A few restarts later however and sometimes they wouldn't work after boot.  

When the hotkeys refuse to function at boot I am able to remedy this simply by going to the desktop and either logging into the regular windows desktop user account or by selecting the Alpha user thus relaunching the hivemind UI.  A few seconds after getting the the login screen the hotkeys kick in and will then continue to function until the next start up.

At first I thought a couple of programs I was attempting to launch at boot were causing this as they would offend hang at the spinning circle on boot.  However after reinstalling hivemind and ensuring there aren't any programs starting with the system the hotkeys end up not working reliably at boot.

**Comment by indidevelopers** [comment]
In next release spinning circle issue will be fixed.

Can you please let us know which controller are you using for hotkeys?

**Comment by dmillerzx** [comment]
This is happening with the x360 controller that shipped with the system.  In addition they also do not function with a PS4 controller hooked up with DS4Windows (not input mapper). 

When the hot keys do function; which appears to be completely random at this point. They will work on both the 360 and PS4 controller.

**Comment by indidevelopers** [comment]
Are you using SSD? Is system Win10 or Win 8.1?

**Comment by dmillerzx** [comment]
SSD, Win 8.1 (fully updated).  Please let me know if I can provide further informaton.

**Comment by indidevelopers** [comment]
Thank you for information. Look like we are able to recreate same issue. We have put fix in next release.

**Comment by dmillerzx** [comment]
FANTASTIC.  You guys rock!  Keep up the great work.

**Comment by indidevelopers** [comment]
If you want, I can send you patched file so you can verify yourself and that we know fix is working.

**Comment by dmillerzx** [comment]
I certainly can verify the fix if you'd like.  I should be able to schedule some time this evening to try it out.   Thanks.

**Comment by indidevelopers** [comment]
PM me your e-mail address so I can send you file to verify

**Comment by indidevelopers** [comment]
Sent download link on your e-mail

**Comment by indidevelopers** [comment]
Today We have push updated . Let us know if this issue is fixed for you
