### ISSUE TITLE
Xbox Windows 10 Sign in Error 0x406

### ISSUE THREAD

**Issue by LilWoofy** [alienwaresoftware/Kodi#8]
I've noticed when you have Kodi/Hivemind installed. It causes an issue where you can't use most of the Microsoft apps such as mail and xbox, When signing in for xbox it says:
"We can't sign you in right now. Try again later.
                                 (0x406)"

And if you open the mail app, nothing happens.

**Comment by indidevelopers** [comment]
This Issue is fixed in internal build. We are going release to all very shortly.

**Comment by indidevelopers** [comment]
Today We have push updated . Let us know if this issue is fixed for you

**Comment by Kristoffeh** [comment]
Not fixed. I am having this issue as we speak! I will update here if it gets fixed.
