### ISSUE TITLE
Stuck in "working" forever after exiting Steam

### ISSUE THREAD

**Issue by reicaden** [alienwaresoftware/Kodi#9]
This has happened consistently and repeatedly since the Hivemind updates. I tried reinstalling the entire system from scratch (Dell USB stick) again later to see if it would resolve with the same issue.
Basically, everything works fine as far as I can tell... I enter steam, I can play a game, exit game, select another game, type, go on the web in steam, everything.

As soon as I "Exit Steam" to go back to the hivemind interface to do something else, the Steam app will exit, the page I was on before entering steam (The games folder) will be open, and a black square that says "Working..." will appear at the bottom right.

I've tried every combination of button presses to exit or move or do anything, and its completely stuck (although the working sign is still spinning on the bottom right square). So it's not really frozen.... its just thinking, and I cant issue a new command until it finishes.
Ive left it on for a couple of days, and yup, still "working' only way Ive found to fix is to physically reset the computer by pressing the Alien button on the unit.

Any assistance would be great... I really dont want to reinstall everything a 3rd time, as it seems to have not fixed the issue anyways when I tried that.

**Comment by indidevelopers** [comment]
Thank for reporting. We will get back to you soon once we have more data and cause of issue.

**Comment by indidevelopers** [comment]
Thanks for your feedback! We were not able to recreate this issue but please try out the beta version at this link to see if the problem you had is resolved: 
https://www.reddit.com/r/AlienwareAlpha/comments/3u940g/hivemind_ui_beta_program/
